[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "bcryptjs"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
